### ISSUE TITLE
Where can I find newest version 0.0.9?

### ISSUE THREAD

**Issue by jhotadhari** [aki12n/multiwindows-highlight#21]
Hi, thanks, does almost exactly what I want.

Want to fork.
Have version `0.0.9` installed via [marketplace](https://marketplace.visualstudio.com/items?itemName=aki12n.multiwindows-highlight).

Here on GitHub, I can find latest version `0.0.4`.

I'm confused, is this the right repository?
I appreciate if you could push latest changes.

thanks

**Comment by aki12n** [comment]
Hi, thanks for using this extension.

I forgot to create the release tag, so I created it.
Please use the latest version of master now.

Thanks

**Comment by aki12n** [comment]
I'm sorry. I realized I forgot to commit.
I just committed the latest version to master, so please use that.

**Comment by jhotadhari** [comment]
thanks a lot!
